replicaCount: 2

image:
  repository: nginxdemos/hello
  pullPolicy: IfNotPresent
  tag: ""

service:
  type: ClusterIP
  port: 80

autoscaling:
  enabled: false

nginx:
  conf:
    message: "AnyTech365 DevOps Helm"
